const PersonnesAout = [
  { numero: 1, nom: "Ngɑ̌pénsīē", jour: "Tuesday" },
  { numero: 2, nom: "Ngòfât", jour: "Wednesday" },
  { numero: 3, nom: "Ngòfât nkèè", jour: "Thursday" },
  { numero: 4, nom: "ɑ́ ngù'bɑ̄ yò", jour: "Friday" },
  { numero: 5, nom: "Ngǔ'ngʉ̄ɑ̄'", jour: "Saturday" },
  { numero: 6, nom: "Ngǔ'nù", jour: "Sunday" },
  { numero: 7, nom: "Ngʉ̄ɑ̄' lɑ̀' míé", jour: "Monday" },
  { numero: 8, nom: "Nì", jour: "Tuesday" },
  { numero: 9, nom: "Njūmɑ̄nì", jour: "Wednesday" },
  { numero: 10, nom: "Ngǎ'mɑ̄nì", jour: "Thursday" },
  { numero: 11, nom: "Njə̀ə̄kām", jour: "Friday" },
  { numero: 12, nom: "Njīìnù", jour: "Saturday" },
  { numero: 13, nom: "Nzhwīènzhì", jour: "Sunday" },
  { numero: 14, nom: "Nǔmbímbōò", jour: "Monday" },
  { numero: 15, nom: "Nǔmbísīē", jour: "Tuesday" },
  { numero: 16, nom: "Nǔmɑ̄nì", jour: "Wednesday" },
  { numero: 17, nom: "Nùpʉ́ɑ́", jour: "Thursday" },
  { numero: 18, nom: "Nùsìmìè", jour: "Friday" },
  { numero: 19, nom: "Nǔwèn", jour: "Saturday" },
  { numero: 20, nom: "Pààngòp", jour: "Sunday" },
  { numero: 21, nom: "Pèè lɑ̀' míé", jour: "Monday" },
  { numero: 22, nom: "Pèè nèhē", jour: "Tuesday" },
  { numero: 23, nom: "Pèèsìnjō", jour: "Wednesday" },
  { numero: 24, nom: "Pǒ'kām", jour: "Thursday" },
  { numero: 25, nom: "Pǒ'sīē", jour: "Friday" },
  { numero: 26, nom: "Sênfə̀", jour: "Saturday" },
  { numero: 27, nom: "Sênfʉ̀", jour: "Sunday" },
  { numero: 38, nom: "Sìàntóó", jour: "Monday" },
  { numero: 29, nom: "Sìdìēmbwèn", jour: "Tuesday" },
  { numero: 30, nom: "Sīēbɑ́nzhī", jour: "Wednesday" },
  { numero: 31, nom: "Ngà'sə̂", jour: "Thursday" }
];

export default PersonnesAout;
