const PersonnesNovembre = [
  { numero: 1, nom: "Còkǒnkām", jour: "Wednesday" },
  { numero: 2, nom: "Sìkɑ̀'", jour: "Thursday" },
  { numero: 3, nom: "Mɑ̄cɑ̄'", jour: "Friday" },
  { numero: 4, nom: "Cōkʉ̀", jour: "Saturday" },
  { numero: 5, nom: "Claire", jour: "Sunday" },
  { numero: 6, nom: "Anne", jour: "Monday" },
  { numero: 7, nom: "Léa", jour: "Tuesday" },
  { numero: 8, nom: "Julie", jour: "Wednesday" },
  { numero: 9, nom: "Antoine", jour: "Thursday" },
  { numero: 10, nom: "Philippe", jour: "Friday" },
  { numero: 11, nom: "Njōmɑ̄lʉ̄ɑ̄'", jour: "Saturday" },
  { numero: 12, nom: "Martin", jour: "Sunday" },
  { numero: 13, nom: "Thomas", jour: "Monday" },
  { numero: 14, nom: "Céline", jour: "Tuesday" },
  { numero: 15, nom: "Louise", jour: "Wednesday" },
  { numero: 16, nom: "Cǎ'cām", jour: "Thursday" },
  { numero: 17, nom: "Jean", jour: "Friday" },
  { numero: 18, nom: "Mireille", jour: "Saturday" },
  { numero: 19, nom: "Hélène", jour: "Sunday" },
  { numero: 20, nom: "Lise", jour: "Monday" },
  { numero: 21, nom: "Vincent", jour: "Tuesday" },
  { numero: 22, nom: "David", jour: "Wednesday" },
  { numero: 23, nom: "Élisabeth", jour: "Thursday" },
  { numero: 24, nom: "Wóktà", jour: "Friday" },
  { numero: 25, nom: "Nicolas", jour: "Saturday" },
  { numero: 26, nom: "Jacques", jour: "Sunday" },
  { numero: 27, nom: "Renée", jour: "Monday" },
  { numero: 28, nom: "Khʉ̄ɑ̄njʉ̀", jour: "Friday" },
  { numero: 29, nom: "Sǐnkāb", jour: "Wenesday" },
  { numero: 30, nom: "Mbè' Nzhì", jour: "Thursday" }
];

export default PersonnesNovembre;
