const personnesJanvier = [
  { numero: 1, nom: "Ngǎ'kò", jour: "Sunday" , nufiJour: "Líé'nkwè’"},
  { numero: 2, nom: "Ncǎ'cwaa", jour: "Monday" , nufiJour: "NKɑ́ɑ́tēē"},
  { numero: 3, nom: "Shwīnāò", jour: "Tuesday" , nufiJour: "Nzêngòò"},
  { numero: 4, nom: "Lə́ə́ncɑ̀'", jour: "Wednesday" , nufiJour: "Ncômntēē"},
  { numero: 5, nom: "Cíéncə̄ə̄", jour: "Thursday" , nufiJour: "Nzîngū"},
  { numero: 6, nom: "Cǎk vɑ̀h", jour: "Friday" , nufiJour: "Nzîsō"},
  { numero: 7, nom: "Tòōkō", jour: "Saturday", nufiJour: "Nsū'kwɑ̀" },
  { numero: 8, nom: "Kɑ̌'mēnī", jour: "Sunday", nufiJour: "Nthʉ̄'ntāā" },
  { numero: 9, nom: "Zhìāndə̀ə̀", jour: "Monday" , nufiJour: "Líé'nkwè’"},
  { numero: 10, nom: "Lə́ə́nkām", jour: "Tuesday" , nufiJour: "NKɑ́ɑ́tēē"},
  { numero: 11, nom: "Mòōnkām", jour: "Wednesday" , nufiJour: "Nzêngòò"},
  { numero: 12, nom: "Ngǎmeni", jour: "Thursday" , nufiJour: "Ncômntēē"},
  { numero: 13, nom: "Hɑāpī", jour: "Friday" , nufiJour: "Nzîngū"},
  { numero: 14, nom: "Tòōkām", jour: "Saturday" , nufiJour: "Nzîsō"},
  { numero: 15, nom: "kòlə̀'kò", jour: "Sunday", nufiJour: "Nsū'kwɑ̀" },
  { numero: 16, nom: "CìēnCə̄", jour: "Monday" , nufiJour: "Nthʉ̄'ntāā"},
  { numero: 17, nom: "Pùālə̄", jour: "Tuesday", nufiJour: "Líé'nkwè’" },
  { numero: 18, nom: "Pùānsī", jour: "Wednesday" , nufiJour: "NKɑ́ɑ́tēē"},
  { numero: 19, nom: "Cāmēnī", jour: "Thursday" , nufiJour: "Nzêngòò"},
  { numero: 20, nom: "Jə̄ngūē", jour: "Friday" , nufiJour: "Ncômntēē"},
  { numero: 21, nom: "Nzhíé'ncə̄ə̄", jour: "Saturday" , nufiJour: "Nzîngū"},
  { numero: 22, nom: "Ntīānngə̄ə̄", jour: "Sunday", nufiJour: "Nzîsō" },
  { numero: 23, nom: "Wěnzhī", jour: "Monday", nufiJour: "Nsū'kwɑ̀" },
  { numero: 24, nom: "Wènkām", jour: "Tuesday" , nufiJour: "Nthʉ̄'ntāā"},
  { numero: 25, nom: "Kàhmɑ̄ncò", jour: "Wednesday" , nufiJour: "Líé'nkwè’"},
  { numero: 26, nom: "Ngə̌nkām", jour: "Thursday" , nufiJour: "NKɑ́ɑ́tēē"},
  { numero: 27, nom: "Ngùnū", jour: "Friday" , nufiJour: "Nzêngòò"},
  { numero: 28, nom: "Njə̄mōō", jour: "Saturday", nufiJour: "Ncômntēē" },
  { numero: 29, nom: "Ngǎ'līɑ̄", jour: "Sunday", nufiJour: "Nzîngū" },
  { numero: 30, nom: "Émo", jour: "Monday", nufiJour: "Nzîsō" },
  { numero: 31, nom: "Kwēnkām", jour: "Tuesday" , nufiJour: "Nsū'kwɑ̀"}
];

export default personnesJanvier;
