const PersonnesJuin = [
  { numero: 1, nom: "Wěnzhī", jour: "Thursday", nufiJour: "Nthʉ̄'ntāā" , month: "Mòmòshʉ̄"},
  { numero: 2, nom: "Ndə̀ə̄nà'", jour: "Friday", nufiJour: "Líé'nkwè’" , month: "Mòmòshʉ̄"},
  { numero: 3, nom: "Ca᷅mjīō", jour: "Saturday", nufiJour: "NKɑ́ɑ́tēē" , month: "Mòmòshʉ̄"},
  { numero: 4, nom: "Mbósīē", jour: "Sunday", nufiJour: "Nzêngòò", month: "Mòmòshʉ̄" },
  { numero: 5, nom: "Mbóncâk", jour: "Monday", nufiJour: "Ncômntēē" , month: "Mòmòshʉ̄"},
  { numero: 6, nom: "Mbōòwèn", jour: "Tuesday", nufiJour: "Nzîngū" , month: "Mòmòshʉ̄"},
  { numero: 7, nom: "Shʉ̄cwɑ̀'", jour: "Wednesday", nufiJour: "Nzîsō" , month: "Mòmòshʉ̄"},
  { numero: 8, nom: "Émāgùām", jour: "Thursday", nufiJour: "Nsū'kwɑ̀" , month: "Mòmòshʉ̄"},
  { numero: 9, nom: "Émākūā", jour: "Friday", nufiJour: "Nthʉ̄'ntāā" , month: "Mòmòshʉ̄"},
  { numero: 10, nom: "Émɑ̄nì", jour: "Saturday", nufiJour: "Líé'nkwè’" , month: "Mòmòshʉ̄"},
  { numero: 11, nom: "Fǎkūālā", jour: "Sunday", nufiJour: "NKɑ́ɑ́tēē" , month: "Mòmòshʉ̄"},
  { numero: 12, nom: "Ndʉɑ̀pèè", jour: "Monday", nufiJour: "Nzêngòò" , month: "Mòmòshʉ̄"},
  { numero: 13, nom: "Njə́ə̀kwɑ̀", jour: "Tuesday", nufiJour: "Ncômntēē" , month: "Mòmòshʉ̄"},
  { numero: 14, nom: "Nzə̌ntēm", jour: "Wednesday", nufiJour: "Nzîngū" , month: "Mòmòshʉ̄"},
  { numero: 15, nom: "Ndə̀ə̄nkām", jour: "Thursday", nufiJour: "Nzîsō" , month: "Mòmòshʉ̄"},
  { numero: 16, nom: "Njòōmbísīē", jour: "Friday", nufiJour: "Nsū'kwɑ̀" , month: "Mòmòshʉ̄"},
  { numero: 17, nom: "Fǎ'nkām", jour: "Saturday", nufiJour: "Nthʉ̄'ntāā" , month: "Mòmòshʉ̄"},
  { numero: 18, nom: "Fə̌' yò", jour: "Sunday", nufiJour: "Líé'nkwè’" , month: "Mòmòshʉ̄"},
  { numero: 19, nom: "Hɑ̄àpìì", jour: "Monday", nufiJour: "NKɑ́ɑ́tēē" , month: "Mòmòshʉ̄"},
  { numero: 20, nom: "Njînù", jour: "Tuesday", nufiJour: "Nzêngòò" , month: "Mòmòshʉ̄"},
  { numero: 21, nom: "Fìágàm", jour: "Wednesday", nufiJour: "Ncômntēē" , month: "Mòmòshʉ̄"},
  { numero: 22, nom: "Sépdə̄", jour: "Thursday", nufiJour: "Nzîngū" , month: "Mòmòshʉ̄"},
  { numero: 23, nom: "Nkǎkmɑ̄nì", jour: "Friday", nufiJour: "Nzîsō" , month: "Mòmòshʉ̄"},
  { numero: 24, nom: "Njūmɑ̄nì", jour: "Saturday", nufiJour: "Nsū'kwɑ̀" , month: "Mòmòshʉ̄"},
  { numero: 25, nom: "Énkòóé", jour: "Sunday", nufiJour: "Nthʉ̄'ntāā" , month: "Mòmòshʉ̄"},
  { numero: 26, nom: "Kèēwū", jour: "Monday", nufiJour: "Líé'nkwè’" , month: "Mòmòshʉ̄"},
  { numero: 27, nom: "Kwèlě'kò", jour: "Tuesday", nufiJour: "NKɑ́ɑ́tēē" , month: "Mòmòshʉ̄"},
  { numero: 28, nom: "Zhínù", jour: "Wenesday", nufiJour: "Nzêngòò" , month: "Mòmòshʉ̄"},
  { numero: 29, nom: "Mīàfə̀", jour: "Thursday", nufiJour: "Ncômntēē" , month: "Mòmòshʉ̄"},
  { numero: 30, nom: "Mbàtkām", jour: "Friday", nufiJour: "Nzîngū" , month: "Mòmòshʉ̄"},
];

export default PersonnesJuin;
