const PersonnesOctobre = [
  { numero: 1, nom: "Zhìāndə̀ə̀", jour: "Sunday", nufiJour: "NKɑ́ɑ́tēē" , month: "Ndǔ'nzɑ̄"},
  { numero: 2, nom: "Yū'mbī'", jour: "Monday", nufiJour: "Nzêngòò" , month: "Ndǔ'nzɑ̄"},
  { numero: 3, nom: "Yū' mbí Sīē", jour: "Tuesday", nufiJour: "Ncômntēē" , month: "Ndǔ'nzɑ̄"},
  { numero: 4, nom: "Mēn à", jour: "Wednesday", nufiJour: "Nzîngū" , month: "Ndǔ'nzɑ̄"},
  { numero: 5, nom: "Nùpɑ́'mbɑ̄hwèn", jour: "Thursday", nufiJour: "Nzîsō" , month: "Ndǔ'nzɑ̄"},
  { numero: 6, nom: "Kǎmbū'", jour: "Friday", nufiJour: "Nsū'kwɑ̀", month: "Ndǔ'nzɑ̄" },
  { numero: 7, nom: "Pǎ'kò", jour: "Saturday", nufiJour: "Nthʉ̄'ntāā" , month: "Ndǔ'nzɑ̄"},
  { numero: 8, nom: "Nkwèèmōō", jour: "Sunday", nufiJour: "Líé'nkwè’" , month: "Ndǔ'nzɑ̄"},
  { numero: 9, nom: "Ndə̀ə̄nkām", jour: "Monday", nufiJour: "NKɑ́ɑ́tēē" , month: "Ndǔ'nzɑ̄"},
  { numero: 10, nom: "Ndə̀ə̄ngwê", jour: "Tuesday", nufiJour: "Nzêngòò" , month: "Ndǔ'nzɑ̄"},
  { numero: 11, nom: "Ca᷅mngwê", jour: "Wednesday", nufiJour: "Ncômntēē" , month: "Ndǔ'nzɑ̄"},
  { numero: 12, nom: "Ngɑ̌pén", jour: "Thursday", nufiJour: "Nzîngū" , month: "Ndǔ'nzɑ̄"},
  { numero: 13, nom: "Mbə̄lòknshì", jour: "Friday", nufiJour: "Nzîsō" , month: "Ndǔ'nzɑ̄"},
  { numero: 14, nom: "Nə̀ə̀simɑ̀'", jour: "Saturday", nufiJour: "Nsū'kwɑ̀" , month: "Ndǔ'nzɑ̄"},
  { numero: 15, nom: "Ŋwâtmbèè", jour: "Sunday", nufiJour: "Nthʉ̄'ntāā" , month: "Ndǔ'nzɑ̄"},
  { numero: 16, nom: "Póónì", jour: "Monday", nufiJour: "Líé'nkwè’" , month: "Ndǔ'nzɑ̄"},
  { numero: 17, nom: "Ngʉ̀ɑ̀'ndʉ̄ɑ̄", jour: "Tuesday", nufiJour: "NKɑ́ɑ́tēē" , month: "Ndǔ'nzɑ̄"},
  { numero: 18, nom: "Mbàtndʉ̄ɑ̄", jour: "Wednesday", nufiJour: "Nzêngòò" , month: "Ndǔ'nzɑ̄"},
  { numero: 19, nom: "Kàhmɑ̄ncò", jour: "Thursday", nufiJour: "Ncômntēē" , month: "Ndǔ'nzɑ̄"},
  { numero: 20, nom: "Ndì Nzhíá'kò", jour: "Friday", nufiJour: "Nzîngū" , month: "Ndǔ'nzɑ̄"},
  { numero: 21, nom: "Mɑ̂nkèè", jour: "Saturday", nufiJour: "Nzîsō" , month: "Ndǔ'nzɑ̄"},
  { numero: 22, nom: "Ngòò Lə́ə́ncə̄ə̄", jour: "Sunday", nufiJour: "Nsū'kwɑ̀" , month: "Ndǔ'nzɑ̄"},
  { numero: 23, nom: "Nzāànzhʉ̀ɑ̀'", jour: "Monday", nufiJour: "Nthʉ̄'ntāā" , month: "Ndǔ'nzɑ̄"},
  { numero: 24, nom: "Mireille", jour: "Tuesday", nufiJour: "Líé'nkwè’" , month: "Ndǔ'nzɑ̄"},
  { numero: 25, nom: "Táàlə̀ə̀", jour: "Wednesday", nufiJour: "NKɑ́ɑ́tēē" , month: "Ndǔ'nzɑ̄"},
  { numero: 26, nom: "Ngòòālə̀ə̀", jour: "Thursday", nufiJour: "Nzêngòò" , month: "Ndǔ'nzɑ̄"},
  { numero: 27, nom: "Nzɑ̂ngwàà", jour: "Friday", nufiJour: "Ncômntēē" , month: "Ndǔ'nzɑ̄"},
  { numero: 28, nom: "Mɑ̄ngwɑ̂'", jour: "Saturday", nufiJour: "Nzîngū" , month: "Ndǔ'nzɑ̄"},
  { numero: 29, nom: "Nshʉ̀ɑ̀ncò", jour: "Sunday", nufiJour: "Nzîsō" , month: "Ndǔ'nzɑ̄"},
  { numero: 30, nom: "Mmɑ̀'ncò", jour: "Monday", nufiJour: "Nsū'kwɑ̀" , month: "Ndǔ'nzɑ̄"},
  { numero: 31, nom: "Táàmɑ̀'ncò", jour: "Tuesday", nufiJour: "Nthʉ̄'ntāā" , month: "Ndǔ'nzɑ̄"},
];

export default PersonnesOctobre;
