const personnesFevrier = [
  { numero: 1, nom: "Njǔkām", jour: 'Wednesday', nufiJour: "Nthʉ̄'ntāā" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 2, nom: "Nzhíá'lə̄ə̄", jour: 'Thursday', nufiJour: "Líé'nkwè’" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 3, nom: "Lǒnàm", jour: 'Friday', nufiJour: "NKɑ́ɑ́tēē", month: "Nkùɑ̀nʉ̀ɑ̀" },
  { numero: 4, nom: "Lǒsīē", jour: 'Saturday', nufiJour: "Nzêngòò" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 5, nom: "Cǎmbū'", jour: 'Sunday', nufiJour: "Ncômntēē" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 6, nom: "Mɑ̂fʉ̀", jour: 'Monday', nufiJour: "Nzîngū" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 7, nom: 'Cìājə̄ə̄', jour: 'Tuesday', nufiJour: "Nzîsō" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 8, nom: "Hāālʉ̄ɑ̄'", jour: 'Wednesday', nufiJour: "Nsū'kwɑ̀" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 9, nom: "Mɑ̄ngátnzhʉ̀'", jour: 'Thursday', nufiJour: "Nthʉ̄'ntāā", month: "Nkùɑ̀nʉ̀ɑ̀" },
  { numero: 10, nom: "Siantóó", jour: 'Friday', nufiJour: "Líé'nkwè’" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 11, nom: "Ngwǎmbe'", jour: 'Saturday', nufiJour: "NKɑ́ɑ́tēē" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 12, nom: "Ntû'kām", jour: "Sunday", nufiJour: "Nzêngòò", month: "Nkùɑ̀nʉ̀ɑ̀" },
  { numero: 13, nom: "Fǎ'nzhʉ̀ɑ̀'", jour: "Monday", nufiJour: "Ncômntēē" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 14, nom: "Cɑ̌nkò", jour: "Tuesday", nufiJour: "Nzîngū", month: "Nkùɑ̀nʉ̀ɑ̀" },
  { numero: 15, nom: "Wókpìì", jour: "Wednesday", nufiJour: "Nzîsō" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 16, nom: "Mênfʉ̀", jour: "Thursday", nufiJour: "Nsū'kwɑ̀" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 17, nom: "Mênkām", jour: "Friday", nufiJour: "Nthʉ̄'ntāā" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 18, nom: "Sīèwèn", jour: "Saturday", nufiJour: "Líé'nkwè’" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 19, nom: "Ndə̌mɑ̄lʉ̄ɑ̄'", jour: "Sunday", nufiJour: "NKɑ́ɑ́tēē" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 20, nom: "Njǒmɑ̄nì", jour: "Monday", nufiJour: "Nzêngòò" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 21, nom: "Cǎmnzhʉ̀ɑ̀'", jour: "Tuesday", nufiJour: "Ncômntēē", month: "Nkùɑ̀nʉ̀ɑ̀" },
  { numero: 22, nom: "Kwèlě'kò", jour: "Wednesday", nufiJour: "Nzîngū" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 23, nom: "Émālə̄/Émɑ̄lʉ̄ɑ̄'", jour: "Thursday", nufiJour: "Nzîsō" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 24, nom: "Ndéndēē", jour: "Friday", nufiJour: "Nsū'kwɑ̀" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 25, nom: "Ndhʉ̌ŋwɑ̄'", jour: "Saturday", nufiJour: "Nthʉ̄'ntāā" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 26, nom: "Ndùāfʉ̀", jour: "Sunday", nufiJour: "Líé'nkwè’" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 27, nom: "Ndùānì", jour: "Monday", nufiJour: "NKɑ́ɑ́tēē" , month: "Nkùɑ̀nʉ̀ɑ̀"},
  { numero: 28, nom: "Mòóngèn", jour: "Tuesday", nufiJour: "Nzêngòò" , month: "Nkùɑ̀nʉ̀ɑ̀"}
];

export default personnesFevrier;
