const PersonnesMai = [
  { numero: 1, nom: "Kēmngūm", jour: "Monday", nufiJour: "Líé'nkwè’" , month: "Njwēnɑ̌hntà"},
  { numero: 2, nom: "Shwínā", jour: "Tuesday", nufiJour: "NKɑ́ɑ́tēē" , month: "Njwēnɑ̌hntà"},
  { numero: 3, nom: "Shwī nā ò", jour: "Wednesday", nufiJour: "Nzêngòò", month: "Njwēnɑ̌hntà" },
  { numero: 4, nom: "Sìdīēmbwèn", jour: "Thursday", nufiJour: "Ncômntēē" , month: "Njwēnɑ̌hntà"},
  { numero: 5, nom: "Sìpīēndɑ̀h", jour: "Friday", nufiJour: "Nzîngū" , month: "Njwēnɑ̌hntà"},
  { numero: 6, nom: "Sipūānkhù", jour: "Saturday", nufiJour: "Nzîsō" , month: "Njwēnɑ̌hntà"},
  { numero: 7, nom: "Sòm Mbūànì", jour: "Sunday", nufiJour: "Nsū'kwɑ̀" , month: "Njwēnɑ̌hntà"},
  { numero: 8, nom: "Tā'sī ā lɑ́", jour: "Monday", nufiJour: "Nthʉ̄'ntāā" , month: "Njwēnɑ̌hntà"},
  { numero: 9, nom: "Tâ'sǐ pè' / pə̀'", jour: "Tuesday", nufiJour: "Líé'nkwè’" , month: "Njwēnɑ̌hntà"},
  { numero: 10, nom: "Títìānì", jour: "Wednesday", nufiJour: "NKɑ́ɑ́tēē" , month: "Njwēnɑ̌hntà"},
  { numero: 11, nom: "Tómnshì", jour: "Thursday", nufiJour: "Nzêngòò" , month: "Njwēnɑ̌hntà"},
  { numero: 12, nom: "Tómnshǐ Nkwè'nì", jour: "Friday", nufiJour: "Ncômntēē" , month: "Njwēnɑ̌hntà"},
  { numero: 13, nom: "Tómnshǐvɑ̀h", jour: "Saturday", nufiJour: "Nzîngū" , month: "Njwēnɑ̌hntà"},
  { numero: 14, nom: "Tʉ̄ɑ̄' mbō nkō", jour: "Sunday", nufiJour: "Nzîsō" , month: "Njwēnɑ̌hntà"},
  { numero: 15, nom: "Tûmbhì", jour: "Monday", nufiJour: "Nsū'kwɑ̀" , month: "Njwēnɑ̌hntà"},
  { numero: 16, nom: "Vɑ̀h zǎ", jour: "Tuesday", nufiJour: "Nthʉ̄'ntāā" , month: "Njwēnɑ̌hntà"},
  { numero: 17, nom: "Vɑ̀h Sʉ̀sʉ̀ɑ̀", jour: "Wednesday", nufiJour: "Líé'nkwè’" , month: "Njwēnɑ̌hntà"},
  { numero: 18, nom: "Wěnsìnēēsī", jour: "Thursday", nufiJour: "NKɑ́ɑ́tēē" , month: "Njwēnɑ̌hntà"},
  { numero: 19, nom: "Wěnsìpūānkhù", jour: "Friday", nufiJour: "Nzêngòò" , month: "Njwēnɑ̌hntà"},
  { numero: 20, nom: "Wū sì lò'", jour: "Saturday", nufiJour: "Ncômntēē" , month: "Njwēnɑ̌hntà"},
  { numero: 21, nom: "Wū sì mbìà", jour: "Sunday", nufiJour: "Nzîngū" , month: "Njwēnɑ̌hntà"},
  { numero: 22, nom: "Yà Póngʉ̀'", jour: "Monday", nufiJour: "Nzîsō" , month: "Njwēnɑ̌hntà"},
  { numero: 23, nom: "Yà Túnù", jour: "Tuesday", nufiJour: "Nsū'kwɑ̀" , month: "Njwēnɑ̌hntà"},
  { numero: 24, nom: "Yā' kwà'", jour: "Wednesday", nufiJour: "Nthʉ̄'ntāā" , month: "Njwēnɑ̌hntà"},
  { numero: 25, nom: "Yām", jour: "Thursday", nufiJour: "Líé'nkwè’" , month: "Njwēnɑ̌hntà"},
  { numero: 26, nom: "Yòmɑ̀ / Yə̀bɑ̀", jour: "Friday", nufiJour: "NKɑ́ɑ́tēē" , month: "Njwēnɑ̌hntà"},
  { numero: 27, nom: "Yōmnā ō ngʉ́", jour: "Saturday", nufiJour: "Nzêngòò" , month: "Njwēnɑ̌hntà"},
  { numero: 28, nom: "Yōpnā ō", jour: "Sunday", nufiJour: "Ncômntēē" , month: "Njwēnɑ̌hntà"},
  { numero: 29, nom: "Yō'sì", jour: "Monday", nufiJour: "Nzîngū" , month: "Njwēnɑ̌hntà"},
  { numero: 30, nom: "Yū'nì", jour: "Tuesday", nufiJour: "Nzîsō" , month: "Njwēnɑ̌hntà"},
  { numero: 31, nom: "Zɑ́h nàm / Zɑ́h nàp", jour: "Wednesday", nufiJour: "Nsū'kwɑ̀" , month: "Njwēnɑ̌hntà"},
];

export default PersonnesMai;
