const PersonnesAvril = [
  { numero: 1, nom: "Nēmālə̄", jour: "Saturday", nufiJour: "Nzêngòò" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 2, nom: "Yū'ngwūɑ̄'", jour: "Sunday", nufiJour: "Ncômntēē", month: "Sò'njɑ̀ɑ̀" },
  { numero: 3, nom: "Ngǎ'lʉ̄ɑ̄'", jour: "Monday", nufiJour: "Nzîngū" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 4, nom: "Nǔlɑ̄'", jour: "Tuesday", nufiJour: "Nzîsō" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 5, nom: "Ngànsōp", jour: "Wednesday", nufiJour: "Nsū'kwɑ̀" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 6, nom: "Nù pɑ́' mbə̄h wèn", jour: "Thursday", nufiJour: "Nthʉ̄'ntāā" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 7, nom: "Ngǔ'nù", jour: "Friday", nufiJour: "Líé'nkwè’" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 8, nom: "Nzhînù", jour: "Saturday", nufiJour: "NKɑ́ɑ́tēē" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 9, nom: "Ngēèsì", jour: "Sunday", nufiJour: "Nzêngòò" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 10, nom: "Ndə᷅nkām", jour: "Monday", nufiJour: "Ncômntēē" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 11, nom: "Yāpsʉ̄'", jour: "Tuesday", nufiJour: "Nzîngū" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 12, nom: "Ngǎmeni", jour: "Wednesday", nufiJour: "Nzîsō" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 13, nom: "CìēnCə̄", jour: "Thursday", nufiJour: "Nsū'kwɑ̀" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 14, nom: "Cāmēnī", jour: "Friday", nufiJour: "Nthʉ̄'ntāā" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 15, nom: "Ngə̌tī", jour: "Saturday", nufiJour: "Líé'nkwè’" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 16, nom: "Pénthʉ̄", jour: "Sunday", nufiJour: "NKɑ́ɑ́tēē" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 17, nom: "Jə̄ngūē", jour: "Monday", nufiJour: "Nzêngòò" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 18, nom: "Wěnzhī", jour: "Tuesday", nufiJour: "Ncômntēē" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 19, nom: "Ngə̌nkām", jour: "Wednesday", nufiJour: "Nzîngū" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 20, nom: "Pànjīī", jour: "Thursday", nufiJour: "Nzîsō" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 21, nom: "Wěnsìcə̄ə̄", jour: "Friday", nufiJour: "Nsū'kwɑ̀" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 22, nom: "Càlə̄", jour: "Saturday", nufiJour: "Nthʉ̄'ntāā" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 23, nom: "Pōh nùsìpè'", jour: "Sunday", nufiJour: "Líé'nkwè’" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 24, nom: "Ngə̄ə̄dām", jour: "Monday", nufiJour: "NKɑ́ɑ́tēē" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 25, nom: "Pàāngōp", jour: "Tuesday", nufiJour: "Nzêngòò" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 26, nom: "Ndʉ̄ɑ̀'ngāā", jour: "Wednesday", nufiJour: "Ncômntēē" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 27, nom: "Còkūāhā", jour: "Thursday", nufiJour: "Nzîngū" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 28, nom: "Ca᷅mjù'", jour: "Friday", nufiJour: "Nzîsō" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 29, nom: "nǔ'tī", jour: "Saturday", nufiJour: "Nsū'kwɑ̀" , month: "Sò'njɑ̀ɑ̀"},
  { numero: 30, nom: "Ngə̄ə̄tī", jour: "Sunday", nufiJour: "Nthʉ̄'ntāā" , month: "Sò'njɑ̀ɑ̀"},
];

export default PersonnesAvril;
