const PersonnesJuillet = [
  { numero: 1, nom: "Líé'nzhì", jour: "Saturday", nufiJour: "Nzîsō", month: "Ntūmbhìngòfāt" },
  { numero: 2, nom: "Mɑ̂fʉ̀", jour: "Sunday", nufiJour: "Nsū'kwɑ̀" , month: "Ntūmbhìngòfāt"},
  { numero: 3, nom: "Mɑ̂fə̀", jour: "Monday", nufiJour: "Nthʉ̄'ntāā" , month: "Ntūmbhìngòfāt"}, 
  { numero: 4, nom: "FāànjƆ̄'", jour: "Tuesday", nufiJour: "Líé'nkwè’" , month: "Ntūmbhìngòfāt"},
  { numero: 5, nom: "Mɑ̂mfə̀n", jour: "Wednesday", nufiJour: "NKɑ́ɑ́tēē" , month: "Ntūmbhìngòfāt"},
  { numero: 6, nom: "Mɑ̄líé'nzhì", jour: "Thursday", nufiJour: "Nzêngòò" , month: "Ntūmbhìngòfāt"},
  { numero: 7, nom: "Mmɑ̀'mbō", jour: "Friday", nufiJour: "Ncômntēē" , month: "Ntūmbhìngòfāt"},
  { numero: 8, nom: "Mɑ̀'ngwɑ̄'", jour: "Saturday", nufiJour: "Nzîngū" , month: "Ntūmbhìngòfāt"},
  { numero: 9, nom: "Mɑ̂pǒ'kām", jour: "Sunday", nufiJour: "Nzîsō" , month: "Ntūmbhìngòfāt"},
  { numero: 10, nom: "Lɑ́'kām", jour: "Monday", nufiJour: "Nsū'kwɑ̀" , month: "Ntūmbhìngòfāt"},
  { numero: 11, nom: "Mɑ̂ntû'kām", jour: "Tuesday", nufiJour: "Nthʉ̄'ntāā" , month: "Ntūmbhìngòfāt"},
  { numero: 12, nom: "Mɑ̂ntû'kām ", jour: "Wednesday", nufiJour: "Líé'nkwè’" , month: "Ntūmbhìngòfāt"},
  { numero: 13, nom: "Mênkām", jour: "Thursday", nufiJour: "NKɑ́ɑ́tēē" , month: "Ntūmbhìngòfāt"},
  { numero: 14, nom: "Nsǐnkāp", jour: "Friday", nufiJour: "Nzêngòò" , month: "Ntūmbhìngòfāt"},
  { numero: 15, nom: "Wókthà", jour: "Saturday", nufiJour: "Ncômntēē" , month: "Ntūmbhìngòfāt"},
  { numero: 16, nom: "Mīàfò", jour: "Sunday", nufiJour: "Nzîngū" , month: "Ntūmbhìngòfāt"},
  { numero: 17, nom: "Mìè mɑ̄ nnák", jour: "Monday", nufiJour: "Nzîsō" , month: "Ntūmbhìngòfāt"},
  { numero: 18, nom: "Mōōntʉ̀ɑ̀'", jour: "Tuesday", nufiJour: "Nsū'kwɑ̀" , month: "Ntūmbhìngòfāt"},
  { numero: 19, nom: "Yòkngwáá", jour: "Wednesday", nufiJour: "Nthʉ̄'ntāā" , month: "Ntūmbhìngòfāt"},
  { numero: 20, nom: "Njə̀ə̄wɑ̄", jour: "Thursday", nufiJour: "Líé'nkwè’" , month: "Ntūmbhìngòfāt"},
  { numero: 21, nom: "Mòōkām", jour: "Friday", nufiJour: "NKɑ́ɑ́tēē" , month: "Ntūmbhìngòfāt"},
  { numero: 22, nom: "Wěnsìpūānkhù", jour: "Saturday", nufiJour: "Nzêngòò" , month: "Ntūmbhìngòfāt"},
  { numero: 23, nom: "Mōònkò'", jour: "Sunday", nufiJour: "Ncômntēē" , month: "Ntūmbhìngòfāt"},
  { numero: 24, nom: "Nnàk mɑ̀ nù", jour: "Monday", nufiJour: "Nzîngū" , month: "Ntūmbhìngòfāt"},
  { numero: 25, nom: "Nēènēē", jour: "Tuesday", nufiJour: "Nzîsō" , month: "Ntūmbhìngòfāt"},
  { numero: 26, nom: "Nɑ̂nnɑ̄n", jour: "Wednesday", nufiJour: "Nsū'kwɑ̀" , month: "Ntūmbhìngòfāt"},
  { numero: 27, nom: "Nɔ̂nɔ̌", jour: "Thursday", nufiJour: "Nthʉ̄'ntāā" , month: "Ntūmbhìngòfāt"},
  { numero: 28, nom: "Ǹ gɑ̀' kɑ́' nù", jour: "Friday", nufiJour: "Líé'nkwè’" , month: "Ntūmbhìngòfāt"},
  { numero: 29, nom: "Ngǎ'kām", jour: "Saturday", nufiJour: "NKɑ́ɑ́tēē" , month: "Ntūmbhìngòfāt"},
  { numero: 30, nom: "Kómnāwèn", jour: "Sunday", nufiJour: "Nzêngòò" , month: "Ntūmbhìngòfāt"},
  { numero: 31, nom: "Kwě'ncò", jour: "Monday", nufiJour: "Ncômntēē" , month: "Ntūmbhìngòfāt"},
];

export default PersonnesJuillet;
