const PersonnesNovembre = [
  { numero: 1, nom: "Còkǒnkām", jour: "Wednesday", nufiJour: "Líé'nkwè’" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 2, nom: "Sìkɑ̀'", jour: "Thursday", nufiJour: "NKɑ́ɑ́tēē" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 3, nom: "Mɑ̄cɑ̄'", jour: "Friday", nufiJour: "Nzêngòò" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 4, nom: "Cōkʉ̀", jour: "Saturday", nufiJour: "Ncômntēē" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 5, nom: "Mòōmɑ̄nì", jour: "Sunday", nufiJour: "Nzîngū" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 6, nom: "Mòówɑ̄", jour: "Monday", nufiJour: "Nzîsō" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 7, nom: "Kǎpnì", jour: "Tuesday", nufiJour: "Nsū'kwɑ̀" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 8, nom: "Mfá'sʉ̄'", jour: "Wednesday", nufiJour: "Nthʉ̄'ntāā" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 9, nom: "Tʉ̄sə̄", jour: "Thursday", nufiJour: "Líé'nkwè’" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 10, nom: "Ncà'", jour: "Friday", nufiJour: "NKɑ́ɑ́tēē" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 11, nom: "Njōmɑ̄lʉ̄ɑ̄'", jour: "Saturday", nufiJour: "Nzêngòò" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 12, nom: "Ndə̀ə̀wɑ̄", jour: "Sunday", nufiJour: "Ncômntēē" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 13, nom: "Cɑ̌'cām", jour: "Monday", nufiJour: "Nzîngū", month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀" },
  { numero: 14, nom: "Cūtā", jour: "Tuesday", nufiJour: "Nzîsō" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 15, nom: "Nə̄tā", jour: "Wednesday", nufiJour: "Nsū'kwɑ̀" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 16, nom: "Njūnāŋ", jour: "Thursday", nufiJour: "Nthʉ̄'ntāā", month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀" },
  { numero: 17, nom: "Nīāmēn", jour: "Friday", nufiJour: "Líé'nkwè’", month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀" },
  { numero: 18, nom: "Fāmēn", jour: "Saturday", nufiJour: "NKɑ́ɑ́tēē" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 19, nom: "Njīmōō", jour: "Sunday", nufiJour: "Nzêngòò" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 20, nom: "Kūāyēp", jour: "Monday", nufiJour: "Ncômntēē" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 21, nom: "Kwām", jour: "Tuesday", nufiJour: "Nzîngū" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 22, nom: "Njitì", jour: "Wednesday", nufiJour: "Nzîsō" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 23, nom: "Njɔ̄nkēp", jour: "Thursday", nufiJour: "Nsū'kwɑ̀" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 24, nom: "Wóktà", jour: "Friday", nufiJour: "Nthʉ̄'ntāā" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 25, nom: "Ngānī", jour: "Saturday", nufiJour: "Líé'nkwè’" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 26, nom: "Càkūntè", jour: "Sunday", nufiJour: "NKɑ́ɑ́tēē" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 27, nom: "Cāwə̄", jour: "Monday", nufiJour: "Nzêngòò" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 28, nom: "Nsǐngá'", jour: "Friday", nufiJour: "Ncômntēē" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 29, nom: "Kòlə̄'kò", jour: "Wenesday", nufiJour: "Nzîngū" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
  { numero: 30, nom: "Mbè' Nzhì", jour: "Thursday", nufiJour: "Nzîsō" , month: "Nkhʉ̀ɑ̀nʉ̀ɑ̀"},
];

export default PersonnesNovembre;
