const PersonnesJuillet = [
  { numero: 1, nom: "Líé'nzhì", jour: "Saturday" },
  { numero: 2, nom: "Mɑ̂fʉ̀", jour: "Sunday" },
  { numero: 3, nom: "Mɑ̂fə̀", jour: "Monday" },
  { numero: 4, nom: "Mâfò", jour: "Tuesday" },
  { numero: 5, nom: "Mɑ̂mfə̀n", jour: "Wednesday" },
  { numero: 6, nom: "Mɑ̄líé'nzhì", jour: "Thursday" },
  { numero: 7, nom: "Mmɑ̀'mbō", jour: "Friday" },
  { numero: 8, nom: "Mɑ̀'ngwɑ̄'", jour: "Saturday" },
  { numero: 9, nom: "Mɑ̂pǒ'kām", jour: "Sunday" },
  { numero: 10, nom: "Lɑ́'kām", jour: "Monday" },
  { numero: 11, nom: "Mɑ̂ntû'kām", jour: "Tuesday" },
  { numero: 12, nom: "Mɑ̂ntû'kām ", jour: "Wednesday" },
  { numero: 13, nom: "Mênkām", jour: "Thursday" },
  { numero: 14, nom: "Mīàfʉ̀", jour: "Friday" },
  { numero: 15, nom: "Mīàfə̀", jour: "Saturday" },
  { numero: 16, nom: "Mīàfò", jour: "Sunday" },
  { numero: 17, nom: "Mìè mɑ̄ nnák", jour: "Monday" },
  { numero: 18, nom: "Mōōntʉ̀ɑ̀'", jour: "Tuesday" },
  { numero: 19, nom: "Yòkngwáá", jour: "Wednesday" },
  { numero: 20, nom: "Njə̀ə̄wɑ̄", jour: "Thursday" },
  { numero: 21, nom: "Mòōkām", jour: "Friday" },
  { numero: 22, nom: "Mòōngwê", jour: "Saturday" },
  { numero: 23, nom: "Mōònkò'", jour: "Sunday" },
  { numero: 24, nom: "Nnàk mɑ̀ nù", jour: "Monday" },
  { numero: 25, nom: "Nēènēē", jour: "Tuesday" },
  { numero: 26, nom: "Nɑ̂nnɑ̄n", jour: "Wednesday" },
  { numero: 27, nom: "Nɔ̂nɔ̌", jour: "Thursday" },
  { numero: 28, nom: "Ǹ gɑ̀' kɑ́' nù", jour: "Friday" },
  { numero: 29, nom: "Ngǎ'kām", jour: "Saturday" },
  { numero: 30, nom: "Kómnāwèn", jour: "Sunday" },
  { numero: 31, nom: "Kwě'ncò", jour: "Monday" }
];

export default PersonnesJuillet;
