const personnesMars = [
  { numero: 1, nom: "Ngà'fʉ̀'", jour: "Wednesday", nufiJour: "Ncômntēē" , month: "Mbàkngòfāt"},
  { numero: 2, nom: "Ngǎngǎ mìè", jour: "Thursday", nufiJour: "Nzîngū" , month: "Mbàkngòfāt"},
  { numero: 3, nom: "Ngòò Mbūànì", jour: "Friday", nufiJour: "Nzîsō" , month: "Mbàkngòfāt"},
  { numero: 4, nom: "Ngʉ̀'", jour: "Saturday", nufiJour: "Nsū'kwɑ̀" , month: "Mbàkngòfāt"},
  { numero: 5, nom: "Ngʉ̀' zǎ", jour: "Sunday", nufiJour: "Nthʉ̄'ntāā" , month: "Mbàkngòfāt"},
  { numero: 6, nom: "Ngʉ̀' zǎ mbú ò", jour: "Monday", nufiJour: "Líé'nkwè’" , month: "Mbàkngòfāt"},
  { numero: 7, nom: "Ngʉ́ɑ́' yá' mìè", jour: "Tuesday", nufiJour: "NKɑ́ɑ́tēē" , month: "Mbàkngòfāt"},
  { numero: 8, nom: "Ngʉ̌' Vɑ̀h", jour: "Wednesday", nufiJour: "Nzêngòò" , month: "Mbàkngòfāt"},
  { numero: 9, nom: "Njû'nì", jour: "Thursday", nufiJour: "Ncômntēē" , month: "Mbàkngòfāt"},
  { numero: 10, nom: "Nkɑ̀'", jour: "Friday", nufiJour: "Nzîngū" , month: "Mbàkngòfāt"},
  { numero: 11, nom: "Nkɑ̌' Ndéndēē", jour: "Saturday", nufiJour: "Nzîsō" , month: "Mbàkngòfāt"},
  { numero: 12, nom: "Nkɑ́' Ngwè'", jour: "Sunday", nufiJour: "Nsū'kwɑ̀" , month: "Mbàkngòfāt"},
  { numero: 13, nom: "Nkɑ̌' Vɑ̀h", jour: "Monday", nufiJour: "Nthʉ̄'ntāā" , month: "Mbàkngòfāt"},
  { numero: 14, nom: "Nkèn Fī", jour: "Tuesday", nufiJour: "Líé'nkwè’" , month: "Mbàkngòfāt"},
  { numero: 15, nom: "Nkômbhìnù", jour: "Wednesday", nufiJour: "NKɑ́ɑ́tēē" , month: "Mbàkngòfāt"},
  { numero: 16, nom: "Nkômnā", jour: "Thursday", nufiJour: "Nzêngòò" , month: "Mbàkngòfāt"},
  { numero: 17, nom: "Nkù'nì", jour: "Friday", nufiJour: "Ncômntēē" , month: "Mbàkngòfāt"},
  { numero: 18, nom: "Nkwà'nù", jour: "Saturday", nufiJour: "Nzîngū" , month: "Mbàkngòfāt"},
  { numero: 19, nom: "Nkwèè yà Fʉ̀'", jour: "Sunday", nufiJour: "Nzîsō" , month: "Mbàkngòfāt"},
  { numero: 20, nom: "Nkwèè yà ngʉ̀'", jour: "Monday", nufiJour: "Nsū'kwɑ̀" , month: "Mbàkngòfāt"},
  { numero: 21, nom: "Nkwè'nì / Nkə̀'nì", jour: "Tuesday", nufiJour: "Nthʉ̄'ntāā" , month: "Mbàkngòfāt"},
  { numero: 22, nom: "Nkwè'nì lɑ̀' míé", jour: "Wednesday", nufiJour: "Líé'nkwè’" , month: "Mbàkngòfāt"},
  { numero: 23, nom: "Nkwè'nì lɑ̀ pé'", jour: "Thursday", nufiJour: "NKɑ́ɑ́tēē" , month: "Mbàkngòfāt"},
  { numero: 24, nom: "Nkwè'nì pōōntìā", jour: "Friday", nufiJour: "Nzêngòò" , month: "Mbàkngòfāt"},
  { numero: 25, nom: "Nsə̀ə̀ Fī", jour: "Saturday", nufiJour: "Ncômntēē" , month: "Mbàkngòfāt"},
  { numero: 26, nom: "Nsə̀ə̀ mā", jour: "Sunday", nufiJour: "Nzîngū", month: "Mbàkngòfāt" },
  { numero: 27, nom: "Nshǐvɑ̀h", jour: "Monday", nufiJour: "Nzîsō" , month: "Mbàkngòfāt"},
  { numero: 28, nom: "Nshʉ̀ɑ̀ncò", jour: "Tuesday", nufiJour: "Nsū'kwɑ̀" , month: "Mbàkngòfāt"},
  { numero: 29, nom: "Nshù'gwè'", jour: "Wednesday", nufiJour: "Nthʉ̄'ntāā" , month: "Mbàkngòfāt"},
  { numero: 30, nom: "Nshwînā", jour: "Thursday", nufiJour: "Líé'nkwè’" , month: "Mbàkngòfāt"},
  { numero: 31, nom: "Ca᷅mnà'", jour: "Friday", nufiJour: "NKɑ́ɑ́tēē" , month: "Mbàkngòfāt"},
];

export default personnesMars;
