const PersonnesDecembre = [
  { numero: 1, nom: "Ngālʉ̄ɑ̄'", jour: "Friday", nufiJour: "Nsū'kwɑ̀"  , month: "Ncátmɑ̄ŋū"},
  { numero: 2, nom: "Nə̄ntā", jour: "Saturday", nufiJour: "Nthʉ̄'ntāā" , month: "Ncátmɑ̄ŋū"},
  { numero: 3, nom: "Nzémé", jour: "Sunday", nufiJour: "Líé'nkwè’"  , month: "Ncátmɑ̄ŋū"},
  { numero: 4, nom: "Ngɑ̌sīē", jour: "Monday", nufiJour: "NKɑ́ɑ́tēē"  , month: "Ncátmɑ̄ŋū"},
  { numero: 5, nom: "Mbīēnàm", jour: "Tuesday", nufiJour: "Nzêngòò"  , month: "Ncátmɑ̄ŋū"},
  { numero: 6, nom: "Ca᷅mkò", jour: "Wednesday" , nufiJour: "Ncômntēē", month: "Ncátmɑ̄ŋū"},
  { numero: 7, nom: "Kāmgà", jour: "Thursday", nufiJour: "Nzîngū"  , month: "Ncátmɑ̄ŋū"},
  { numero: 8, nom: "Cālə̄", jour: "Friday", nufiJour: "Nzîsō"  , month: "Ncátmɑ̄ŋū"},
  { numero: 9, nom: "Tūāsī", jour: "Saturday" , nufiJour: "Nsū'kwɑ̀", month: "Ncátmɑ̄ŋū"},
  { numero: 10, nom: "Ngə̌nkām", jour: "Sunday" , nufiJour: "Nthʉ̄'ntāā", month: "Ncátmɑ̄ŋū"},
  { numero: 11, nom: "Hɑ̄ālʉ̄ɑ̄'", jour: "Monday", nufiJour: "Líé'nkwè’"  , month: "Ncátmɑ̄ŋū"},
  { numero: 12, nom: "Ndə̄nkāp", jour: "Tuesday", nufiJour: "NKɑ́ɑ́tēē" , month: "Ncátmɑ̄ŋū"},
  { numero: 13, nom: "Ndʉ̀mbʉ́ɑ́", jour: "Wednesday", nufiJour: "Nzêngòò"   , month: "Ncátmɑ̄ŋū"},
  { numero: 14, nom: "Ndʉ̀ndām", jour: "Thursday" , nufiJour: "Ncômntēē" , month: "Ncátmɑ̄ŋū"},
  { numero: 15, nom: "Ngʉ̀ɑ̀'ndʉ̄ɑ̄", jour: "Friday", nufiJour: "Nzîngū" , month: "Ncátmɑ̄ŋū"},
  { numero: 16, nom: "Mfìènkàk", jour: "Saturday", nufiJour: "Nzîsō"  , month: "Ncátmɑ̄ŋū"},
  { numero: 17, nom: "Mbūānì", jour: "Sunday", nufiJour: "Nsū'kwɑ̀" , month: "Ncátmɑ̄ŋū"},
  { numero: 18, nom: "Cìēncə̄ə̄", jour: "Monday" , nufiJour: "Nthʉ̄'ntāā", month: "Ncátmɑ̄ŋū"},
  { numero: 19, nom: "Mbʉ̄ʉ̄", jour: "Tuesday" , nufiJour: "Líé'nkwè’" , month: "Ncátmɑ̄ŋū"},
  { numero: 20, nom: "Lǒnàm", jour: "Wednesday" , nufiJour: "NKɑ́ɑ́tēē", month: "Ncátmɑ̄ŋū"},
  { numero: 21, nom: "Kèə̄vɑ̀h", jour: "Thursday" , nufiJour: "Nzêngòò"  , month: "Ncátmɑ̄ŋū"},
  { numero: 22, nom: "Táàlə̀ə̀", jour: "Friday" , nufiJour: "Ncômntēē" , month: "Ncátmɑ̄ŋū"},
  { numero: 23, nom: "Ngòòālə̀ə̀", jour: "Saturday", nufiJour: "Nzîngū" , month: "Ncátmɑ̄ŋū"},
  { numero: 24, nom: "Ngālə̄", jour: "Sunday" , nufiJour: "Nzîsō" , month: "Ncátmɑ̄ŋū"},
  { numero: 25, nom: "Nǐncə̄ə̄", jour: "Monday" , nufiJour: "Nsū'kwɑ̀", month: "Ncátmɑ̄ŋū"},
  { numero: 26, nom: "Mɑ̄lū'", jour: "Tuesday" , nufiJour: "Nthʉ̄'ntāā", month: "Ncátmɑ̄ŋū"},
  { numero: 27, nom: "Njə̀ə̄ngà'", jour: "Wednesday" , nufiJour: "Líé'nkwè’" , month: "Ncátmɑ̄ŋū"},
  { numero: 28, nom: "Ndɑ̌'sīē", jour: "Thursday", nufiJour: "NKɑ́ɑ́tēē" , month: "Ncátmɑ̄ŋū"},
  { numero: 29, nom: "Cīēnkām", jour: "Friday" , nufiJour: "Nzêngòò"  , month: "Ncátmɑ̄ŋū"},
  { numero: 30, nom: "Yū'mbī'", jour: "Saturday" , nufiJour: "Ncômntēē" , month: "Ncátmɑ̄ŋū"},
  { numero: 31, nom: "Yámngà'", jour: "Sunday", nufiJour: "Nzîngū" , month: "Ncátmɑ̄ŋū"},
];

export default PersonnesDecembre;
