const PersonnesAout = [
  { numero: 1, nom: "Nkɑ̀'zhī", jour: "Tuesday", nufiJour: "Nzîngū" , month: "Mɑ̄ngà'nshì"},
  { numero: 2, nom: "Ngòfât", jour: "Wednesday", nufiJour: "Nzîsō" , month: "Mɑ̄ngà'nshì"},
  { numero: 3, nom: "Ngòfât nkèè", jour: "Thursday", nufiJour: "Nsū'kwɑ̀" , month: "Mɑ̄ngà'nshì"},
  { numero: 4, nom: "ɑ́ ngù'bɑ̄ yò", jour: "Friday", nufiJour: "Nthʉ̄'ntāā" , month: "Mɑ̄ngà'nshì"},
  { numero: 5, nom: "Ngǔ'ngʉ̄ɑ̄'", jour: "Saturday", nufiJour: "Líé'nkwè’" , month: "Mɑ̄ngà'nshì"},
  { numero: 6, nom: "Ngǔ'nù", jour: "Sunday", nufiJour: "NKɑ́ɑ́tēē", month: "Mɑ̄ngà'nshì" },
  { numero: 7, nom: "Ngʉ̄ɑ̄'lɑ̀'míé", jour: "Monday", nufiJour: "Nzêngòò", month: "Mɑ̄ngà'nshì" },
  { numero: 8, nom: "Nì", jour: "Tuesday", nufiJour: "Ncômntēē" , month: "Mɑ̄ngà'nshì"},
  { numero: 9, nom: "Nkɑ̀'ncò", jour: "Wednesday", nufiJour: "Nzîngū" , month: "Mɑ̄ngà'nshì"},
  { numero: 10, nom: "Ngǎ'mɑ̄nì", jour: "Thursday", nufiJour: "Nzîsō", month: "Mɑ̄ngà'nshì" },
  { numero: 11, nom: "Njə̀ə̄kām", jour: "Friday", nufiJour: "Nsū'kwɑ̀" , month: "Mɑ̄ngà'nshì"},
  { numero: 12, nom: "Njīìnù", jour: "Saturday", nufiJour: "Nthʉ̄'ntāā" , month: "Mɑ̄ngà'nshì"},
  { numero: 13, nom: "Nzhwīènzhì", jour: "Sunday", nufiJour: "Líé'nkwè’" , month: "Mɑ̄ngà'nshì"},
  { numero: 14, nom: "Nǔmbímbōò", jour: "Monday", nufiJour: "NKɑ́ɑ́tēē" , month: "Mɑ̄ngà'nshì"},
  { numero: 15, nom: "Nǔmbísīē", jour: "Tuesday", nufiJour: "Nzêngòò" , month: "Mɑ̄ngà'nshì"},
  { numero: 16, nom: "Nǔmɑ̄nì", jour: "Wednesday", nufiJour: "Ncômntēē" , month: "Mɑ̄ngà'nshì"},
  { numero: 17, nom: "Nùpʉ́ɑ́", jour: "Thursday", nufiJour: "Nzîngū" , month: "Mɑ̄ngà'nshì"},
  { numero: 18, nom: "Nùsìmìè", jour: "Friday", nufiJour: "Nzîsō" , month: "Mɑ̄ngà'nshì"},
  { numero: 19, nom: "Nǔwèn", jour: "Saturday", nufiJour: "Nsū'kwɑ̀" , month: "Mɑ̄ngà'nshì"},
  { numero: 20, nom: "Pààngòp", jour: "Sunday", nufiJour: "Nthʉ̄'ntāā" , month: "Mɑ̄ngà'nshì"},
  { numero: 21, nom: "Pèè lɑ̀' míé", jour: "Monday", nufiJour: "Líé'nkwè’" , month: "Mɑ̄ngà'nshì"},
  { numero: 22, nom: "Pèè nèhē", jour: "Tuesday", nufiJour: "NKɑ́ɑ́tēē" , month: "Mɑ̄ngà'nshì"},
  { numero: 23, nom: "Pèèsìnjō", jour: "Wednesday", nufiJour: "Nzêngòò" , month: "Mɑ̄ngà'nshì"},
  { numero: 24, nom: "Pǒ'kām", jour: "Thursday", nufiJour: "Ncômntēē", month: "Mɑ̄ngà'nshì" },
  { numero: 25, nom: "Pǒ'sīē", jour: "Friday", nufiJour: "Nzîngū" , month: "Mɑ̄ngà'nshì"},
  { numero: 26, nom: "Sênfə̀", jour: "Saturday", nufiJour: "Nzîsō" , month: "Mɑ̄ngà'nshì"},
  { numero: 27, nom: "Sênfʉ̀", jour: "Sunday", nufiJour: "Nsū'kwɑ̀" , month: "Mɑ̄ngà'nshì"},
  { numero: 38, nom: "Sìàntóó", jour: "Monday", nufiJour: "Nthʉ̄'ntāā" , month: "Mɑ̄ngà'nshì"},
  { numero: 29, nom: "Sìdìēmbwèn", jour: "Tuesday", nufiJour: "Líé'nkwè’" , month: "Mɑ̄ngà'nshì"},
  { numero: 30, nom: "Sīēbɑ́nzhī", jour: "Wednesday", nufiJour: "NKɑ́ɑ́tēē" , month: "Mɑ̄ngà'nshì"},
  { numero: 31, nom: "Ngà'sə̂", jour: "Thursday", nufiJour: "Nzêngòò" , month: "Mɑ̄ngà'nshì"},
];

export default PersonnesAout;
