const PersonnesNovembre = [
  { numero: 1, nom: "Còkǒnkām", jour: "Wednesday", nufiJour: "Líé'nkwè’" },
  { numero: 2, nom: "Sìkɑ̀'", jour: "Thursday", nufiJour: "NKɑ́ɑ́tēē" },
  { numero: 3, nom: "Mɑ̄cɑ̄'", jour: "Friday", nufiJour: "Nzêngòò" },
  { numero: 4, nom: "Cōkʉ̀", jour: "Saturday", nufiJour: "Ncômntēē" },
  { numero: 5, nom: "Claire", jour: "Sunday", nufiJour: "Nzîngū" },
  { numero: 6, nom: "Anne", jour: "Monday", nufiJour: "Nzîsō" },
  { numero: 7, nom: "Léa", jour: "Tuesday", nufiJour: "Nsū'kwɑ̀" },
  { numero: 8, nom: "Julie", jour: "Wednesday", nufiJour: "Nthʉ̄'ntāā" },
  { numero: 9, nom: "Antoine", jour: "Thursday", nufiJour: "Líé'nkwè’" },
  { numero: 10, nom: "Philippe", jour: "Friday", nufiJour: "NKɑ́ɑ́tēē" },
  { numero: 11, nom: "Njōmɑ̄lʉ̄ɑ̄'", jour: "Saturday", nufiJour: "Nzêngòò" },
  { numero: 12, nom: "Martin", jour: "Sunday", nufiJour: "Ncômntēē" },
  { numero: 13, nom: "Thomas", jour: "Monday", nufiJour: "Nzîngū" },
  { numero: 14, nom: "Céline", jour: "Tuesday", nufiJour: "Nzîsō" },
  { numero: 15, nom: "Louise", jour: "Wednesday", nufiJour: "Nsū'kwɑ̀" },
  { numero: 16, nom: "Cǎ'cām", jour: "Thursday", nufiJour: "Nthʉ̄'ntāā" },
  { numero: 17, nom: "Jean", jour: "Friday", nufiJour: "Líé'nkwè’" },
  { numero: 18, nom: "Mireille", jour: "Saturday", nufiJour: "NKɑ́ɑ́tēē" },
  { numero: 19, nom: "Hélène", jour: "Sunday", nufiJour: "Nzêngòò" },
  { numero: 20, nom: "Lise", jour: "Monday", nufiJour: "Ncômntēē" },
  { numero: 21, nom: "Vincent", jour: "Tuesday", nufiJour: "Nzîngū" },
  { numero: 22, nom: "David", jour: "Wednesday", nufiJour: "Nzîsō" },
  { numero: 23, nom: "Élisabeth", jour: "Thursday", nufiJour: "Nsū'kwɑ̀" },
  { numero: 24, nom: "Wóktà", jour: "Friday", nufiJour: "Nthʉ̄'ntāā" },
  { numero: 25, nom: "Nicolas", jour: "Saturday", nufiJour: "Líé'nkwè’" },
  { numero: 26, nom: "Jacques", jour: "Sunday", nufiJour: "NKɑ́ɑ́tēē" },
  { numero: 27, nom: "Renée", jour: "Monday", nufiJour: "Nzêngòò" },
  { numero: 28, nom: "Khʉ̄ɑ̄njʉ̀", jour: "Friday", nufiJour: "Ncômntēē" },
  { numero: 29, nom: "Sǐnkāb", jour: "Wenesday", nufiJour: "Nzîngū" },
  { numero: 30, nom: "Mbè' Nzhì", jour: "Thursday", nufiJour: "Nzîsō" }
];

export default PersonnesNovembre;
