const PersonnesDecembre = [
  { numero: 1, nom: "Gaston", jour: "Friday" },
  { numero: 2, nom: "Marie", jour: "Saturday" },
  { numero: 3, nom: "Lucie", jour: "Sunday" },
  { numero: 4, nom: "Charles", jour: "Monday" },
  { numero: 5, nom: "Pierre", jour: "Tuesday" },
  { numero: 6, nom: "François", jour: "Wednesday" },
  { numero: 7, nom: "Sophie", jour: "Thursday>" },
  { numero: 8, nom: "Étienne", jour: "Friday" },
  { numero: 9, nom: "Claire", jour: "Saturday" },
  { numero: 10, nom: "Anne", jour: "Sunday" },
  { numero: 11, nom: "Léa", jour: "Monday" },
  { numero: 12, nom: "Ndə̄nkāp", jour: "Tuesday" },
  { numero: 13, nom: "Antoine", jour: "Wednesday" },
  { numero: 14, nom: "Philippe", jour: "Tthursday" },
  { numero: 15, nom: "Nathalie", jour: "Friday" },
  { numero: 16, nom: "Martin", jour: "Saturday" },
  { numero: 17, nom: "Thomas", jour: "Sunday" },
  { numero: 18, nom: "Cìēncə̄ə̄", jour: "Monday" },
  { numero: 19, nom: "Gaston", jour: "Tuesday" },
  { numero: 20, nom: "Paul", jour: "Wednesday" },
  { numero: 21, nom: "Jean", jour: "Thursday" },
  { numero: 22, nom: "Mireille", jour: "Friday" },
  { numero: 23, nom: "Jean-Michel", jour: "Saturday" },
  { numero: 24, nom: "Claude", jour: "Sunday" },
  { numero: 25, nom: "Vincent", jour: "Monday" },
  { numero: 26, nom: "David", jour: "Tuesday" },
  { numero: 27, nom: "Élisabeth", jour: "Wednesday" },
  { numero: 28, nom: "Ndɑ̌'sīē", jour: "Thursday" },
  { numero: 29, nom: "Yū'mbí", jour: "Friday" },
  { numero: 30, nom: "Yū'mbī'", jour: "Saturday" },
  { numero: 31, nom: "Benjamin", jour: "Sunday" },
];

export default PersonnesDecembre;
