const PersonnesDecembre = [
  { numero: 1, nom: "Gaston", jour: "Friday", nufiJour: "Nsū'kwɑ̀"  },
  { numero: 2, nom: "Marie", jour: "Saturday", nufiJour: "Nthʉ̄'ntāā" },
  { numero: 3, nom: "Lucie", jour: "Sunday", nufiJour: "Líé'nkwè’"  },
  { numero: 4, nom: "Charles", jour: "Monday", nufiJour: "NKɑ́ɑ́tēē"  },
  { numero: 5, nom: "Pierre", jour: "Tuesday", nufiJour: "Nzêngòò"  },
  { numero: 6, nom: "François", jour: "Wednesday" , nufiJour: "Ncômntēē"},
  { numero: 7, nom: "Sophie", jour: "Thursday>", nufiJour: "Nzîngū"  },
  { numero: 8, nom: "Étienne", jour: "Friday", nufiJour: "Nzîsō"  },
  { numero: 9, nom: "Claire", jour: "Saturday" , nufiJour: "Nsū'kwɑ̀"},
  { numero: 10, nom: "Anne", jour: "Sunday" , nufiJour: "Nthʉ̄'ntāā"},
  { numero: 11, nom: "Léa", jour: "Monday", nufiJour: "Líé'nkwè’"  },
  { numero: 12, nom: "Ndə̄nkāp", jour: "Tuesday", nufiJour: "NKɑ́ɑ́tēē" },
  { numero: 13, nom: "Antoine", jour: "Wednesday", nufiJour: "Nzêngòò"   },
  { numero: 14, nom: "Philippe", jour: "Tthursday" , nufiJour: "Ncômntēē" },
  { numero: 15, nom: "Nathalie", jour: "Friday", nufiJour: "Nzîngū" },
  { numero: 16, nom: "Martin", jour: "Saturday", nufiJour: "Nzîsō"  },
  { numero: 17, nom: "Thomas", jour: "Sunday", nufiJour: "Nsū'kwɑ̀" },
  { numero: 18, nom: "Cìēncə̄ə̄", jour: "Monday" , nufiJour: "Nthʉ̄'ntāā"},
  { numero: 19, nom: "Gaston", jour: "Tuesday" , nufiJour: "Líé'nkwè’" },
  { numero: 20, nom: "Paul", jour: "Wednesday" , nufiJour: "NKɑ́ɑ́tēē"},
  { numero: 21, nom: "Jean", jour: "Thursday" , nufiJour: "Nzêngòò"  },
  { numero: 22, nom: "Mireille", jour: "Friday" , nufiJour: "Ncômntēē" },
  { numero: 23, nom: "Jean-Michel", jour: "Saturday", nufiJour: "Nzîngū" },
  { numero: 24, nom: "Claude", jour: "Sunday" , nufiJour: "Nzîsō" },
  { numero: 25, nom: "Vincent", jour: "Monday" , nufiJour: "Nsū'kwɑ̀"},
  { numero: 26, nom: "David", jour: "Tuesday" , nufiJour: "Nthʉ̄'ntāā"},
  { numero: 27, nom: "Élisabeth", jour: "Wednesday" , nufiJour: "Líé'nkwè’" },
  { numero: 28, nom: "Ndɑ̌'sīē", jour: "Thursday", nufiJour: "NKɑ́ɑ́tēē" },
  { numero: 29, nom: "Yū'mbí", jour: "Friday" , nufiJour: "Nzêngòò"  },
  { numero: 30, nom: "Yū'mbī'", jour: "Saturday" , nufiJour: "Ncômntēē" },
  { numero: 31, nom: "Benjamin", jour: "Sunday", nufiJour: "Nzîngū" },
];

export default PersonnesDecembre;
