const PersonnesAvril = [
  { numero: 1, nom: "Ntōòvɑ̀h", jour: "Saturday"  },
  { numero: 2, nom: "Lə́ə́ncɑ̀'" , jour: "Sunday" },
  { numero: 3, nom: "Ca᷅mnà'" , jour: "Monday" },
  { numero: 4, nom: "Nǔlɑ̄'", jour: "Tuesday"  },
  { numero: 5, nom: "Nù lɑ̀' pə̄h wèn ntìā", jour: "Wednesday"  },
  { numero: 6, nom: "Nù pɑ́' mbə̄h wèn" , jour: "Thursday" },
  { numero: 7, nom: "Nzɑ́ lēē" , jour: "Friday" },
  { numero: 8, nom: "Nzhînù" , jour: "Saturday" },
  { numero: 9, nom: "Nzhînùwèn" , jour: "Sunday" },
  { numero: 10, nom: "Ndə᷅nkām" , jour: "Monday" },
  { numero: 11, nom: "Mòōnkām" , jour: "Tuesday" },
  { numero: 12, nom: "Ngǎmeni" , jour: "Wednesday" },
  { numero: 13, nom: "CìēnCə̄" , jour: "Thursday" },
  { numero: 14, nom: "Cāmēnī" , jour: "Friday" },
  { numero: 15, nom: "Pè'nì" , jour: "Saturday" },
  { numero: 16, nom: "Pénthʉ̄" , jour: "Sunday" },
  { numero: 17, nom: "Jə̄ngūē" , jour: "Monday" },
  { numero: 18, nom: "Wěnzhī", jour: "Tuesday"  },
  { numero: 19, nom: "Ngə̌nkām" , jour: "Wednesday" },
  { numero: 20, nom: "Pànjīī" , jour: "Thursday" },
  { numero: 21, nom: "Wěnsìcə̄ə̄", jour: "Friday"  },
  { numero: 22, nom: "Càlə̄" , jour: "Saturday" },
  { numero: 23, nom: "Pōh nùsìpè'" , jour: "Sunday" },
  { numero: 24, nom: "Pó ngʉ̀'", jour: "Monday"  },
  { numero: 25, nom: "Pàāngōp" , jour: "Tuesday" },
  { numero: 26, nom: "Cāmgúé" , jour: "Wednesday" },
  { numero: 27, nom: "Còkūāhā" , jour: "Thursday" },
  { numero: 28, nom: "Ca᷅mjù'" , jour: "Friday" },
  { numero: 29, nom: "Nùctī" , jour: "Saturday" },
  { numero: 30, nom: "Ngə̄ə̄tī", jour: "Sunday"  }
];

export default PersonnesAvril;
