const personnesFevrier = [
  { numero: 1, nom: "Làmsí nshù", jour: 'Wednesday', nufiJour: "Nthʉ̄'ntāā" },
  { numero: 2, nom: "Lə̌hmbhì", jour: 'Thursday', nufiJour: "Líé'nkwè’" },
  { numero: 3, nom: "Lǒnàm", jour: 'Friday', nufiJour: "NKɑ́ɑ́tēē" },
  { numero: 4, nom: "Lǒsīē", jour: 'Saturday', nufiJour: "Nzêngòò" },
  { numero: 5, nom: "Lǒsīē nnák", jour: 'Sunday', nufiJour: "Ncômntēē" },
  { numero: 6, nom: "Mɑ̂fʉ̀", jour: 'Monday', nufiJour: "Nzîngū" },
  { numero: 7, nom: 'Mɑ̂fʉ̀ Mbūànì', jour: 'Tuesday', nufiJour: "Nzîsō" },
  { numero: 8, nom: "Mɑ̂fʉ̀ nkō'", jour: 'Wednesday', nufiJour: "Nsū'kwɑ̀" },
  { numero: 9, nom: "Mɑ̄ngátnzhʉ̀'", jour: 'Thursday', nufiJour: "Nthʉ̄'ntāā" },
  { numero: 10, nom: "Mbè' Cwè'", jour: 'Friday', nufiJour: "Líé'nkwè’" },
  { numero: 11, nom: "Mbè' Nɑ̄h", jour: 'Saturday', nufiJour: "NKɑ́ɑ́tēē" },
  { numero: 12, nom: "Mbè'zīī", jour: "Sunday", nufiJour: "Nzêngòò" },
  { numero: 13, nom: "Mbó Fʉ̀'", jour: "Monday", nufiJour: "Ncômntēē" },
  { numero: 14, nom: "Mbūànì", jour: "Tuesday", nufiJour: "Nzîngū" },
  { numero: 15, nom: "Mbūànì Wèn", jour: "Wednesday", nufiJour: "Nzîsō" },
  { numero: 16, nom: "Mênfʉ̀", jour: "Thursday", nufiJour: "Nsū'kwɑ̀" },
  { numero: 17, nom: "Mênkām", jour: "Friday", nufiJour: "Nthʉ̄'ntāā" },
  { numero: 18, nom: "Mfɑ̀'ndīēkò", jour: "Saturday", nufiJour: "Líé'nkwè’" },
  { numero: 19, nom: "Nɑ́h nkwè'nì", jour: "Sunday", nufiJour: "NKɑ́ɑ́tēē" },
  { numero: 20, nom: "Nɑ́h vɑ̀h", jour: "Monday", nufiJour: "Nzêngòò" },
  { numero: 21, nom: "Nàm", jour: "Tuesday", nufiJour: "Ncômntēē" },
  { numero: 22, nom: "Nàm à", jour: "Wednesday", nufiJour: "Nzîngū" },
  { numero: 23, nom: "Ncǎ' miè", jour: "Thursday", nufiJour: "Nzîsō" },
  { numero: 24, nom: "Ndéndēē", jour: "Friday", nufiJour: "Nsū'kwɑ̀" },
  { numero: 25, nom: "Ndhʉ̌ŋwɑ̄'", jour: "Saturday", nufiJour: "Nthʉ̄'ntāā" },
  { numero: 26, nom: "Ndùāfʉ̀", jour: "Sunday", nufiJour: "Líé'nkwè’" },
  { numero: 27, nom: "Ndùānì", jour: "Monday", nufiJour: "NKɑ́ɑ́tēē" },
  { numero: 28, nom: "Ndʉ̄ɑ̀'lɑ̄'", jour: "Tuesday", nufiJour: "Nzêngòò" }
];

export default personnesFevrier;
