const PersonnesAvril = [
  { numero: 1, nom: "Ntōòvɑ̀h", jour: "Saturday", nufiJour: "Nzêngòò" },
  { numero: 2, nom: "Lə́ə́ncɑ̀'", jour: "Sunday", nufiJour: "Ncômntēē" },
  { numero: 3, nom: "Ca᷅mnà'", jour: "Monday", nufiJour: "Nzîngū" },
  { numero: 4, nom: "Nǔlɑ̄'", jour: "Tuesday", nufiJour: "Nzîsō" },
  { numero: 5, nom: "Nù lɑ̀' pə̄h wèn ntìā", jour: "Wednesday", nufiJour: "Nsū'kwɑ̀" },
  { numero: 6, nom: "Nù pɑ́' mbə̄h wèn", jour: "Thursday", nufiJour: "Nthʉ̄'ntāā" },
  { numero: 7, nom: "Nzɑ́ lēē", jour: "Friday", nufiJour: "Líé'nkwè’" },
  { numero: 8, nom: "Nzhînù", jour: "Saturday", nufiJour: "NKɑ́ɑ́tēē" },
  { numero: 9, nom: "Nzhînùwèn", jour: "Sunday", nufiJour: "Nzêngòò" },
  { numero: 10, nom: "Ndə᷅nkām", jour: "Monday", nufiJour: "Ncômntēē" },
  { numero: 11, nom: "Mòōnkām", jour: "Tuesday", nufiJour: "Nzîngū" },
  { numero: 12, nom: "Ngǎmeni", jour: "Wednesday", nufiJour: "Nzîsō" },
  { numero: 13, nom: "CìēnCə̄", jour: "Thursday", nufiJour: "Nsū'kwɑ̀" },
  { numero: 14, nom: "Cāmēnī", jour: "Friday", nufiJour: "Nthʉ̄'ntāā" },
  { numero: 15, nom: "Pè'nì", jour: "Saturday", nufiJour: "Líé'nkwè’" },
  { numero: 16, nom: "Pénthʉ̄", jour: "Sunday", nufiJour: "NKɑ́ɑ́tēē" },
  { numero: 17, nom: "Jə̄ngūē", jour: "Monday", nufiJour: "Nzêngòò" },
  { numero: 18, nom: "Wěnzhī", jour: "Tuesday", nufiJour: "Ncômntēē" },
  { numero: 19, nom: "Ngə̌nkām", jour: "Wednesday", nufiJour: "Nzîngū" },
  { numero: 20, nom: "Pànjīī", jour: "Thursday", nufiJour: "Nzîsō" },
  { numero: 21, nom: "Wěnsìcə̄ə̄", jour: "Friday", nufiJour: "Nsū'kwɑ̀" },
  { numero: 22, nom: "Càlə̄", jour: "Saturday", nufiJour: "Nthʉ̄'ntāā" },
  { numero: 23, nom: "Pōh nùsìpè'", jour: "Sunday", nufiJour: "Líé'nkwè’" },
  { numero: 24, nom: "Pó ngʉ̀'", jour: "Monday", nufiJour: "NKɑ́ɑ́tēē" },
  { numero: 25, nom: "Pàāngōp", jour: "Tuesday", nufiJour: "Nzêngòò" },
  { numero: 26, nom: "Cāmgúé", jour: "Wednesday", nufiJour: "Ncômntēē" },
  { numero: 27, nom: "Còkūāhā", jour: "Thursday", nufiJour: "Nzîngū" },
  { numero: 28, nom: "Ca᷅mjù'", jour: "Friday", nufiJour: "Nzîsō" },
  { numero: 29, nom: "Nùctī", jour: "Saturday", nufiJour: "Nsū'kwɑ̀" },
  { numero: 30, nom: "Ngə̄ə̄tī", jour: "Sunday", nufiJour: "Nthʉ̄'ntāā" }
];

export default PersonnesAvril;
