const PersonnesJuin = [
  { numero: 1, nom: "Mbàkngòfāt", jour: "Thursday", nufiJour: "Nthʉ̄'ntāā" },
  { numero: 2, nom: "Mbɑ̀ lāhā lɑ̄", jour: "Friday", nufiJour: "Líé'nkwè’" },
  { numero: 3, nom: "Mbǔ'zhíkɑ́", jour: "Saturday", nufiJour: "NKɑ́ɑ́tēē" },
  { numero: 4, nom: "Mbósīē", jour: "Sunday", nufiJour: "Nzêngòò" },
  { numero: 5, nom: "Mbóncâk", jour: "Monday", nufiJour: "Ncômntēē" },
  { numero: 6, nom: "Mbōòwèn", jour: "Tuesday", nufiJour: "Nzîngū" },
  { numero: 7, nom: "Shʉ̄cwɑ̀'", jour: "Wednesday", nufiJour: "Nzîsō" },
  { numero: 8, nom: "Nshǔndênù", jour: "Thursday", nufiJour: "Nsū'kwɑ̀" },
  { numero: 9, nom: "Ndɑ̌'kɑ́yīī", jour: "Friday", nufiJour: "Nthʉ̄'ntāā" },
  { numero: 10, nom: "Ndɑ̌'sīē", jour: "Saturday", nufiJour: "Líé'nkwè’" },
  { numero: 11, nom: "Ǹ dɑ̀yíí nù", jour: "Sunday", nufiJour: "NKɑ́ɑ́tēē" },
  { numero: 12, nom: "Ndʉɑ̀pèè", jour: "Monday", nufiJour: "Nzêngòò" },
  { numero: 13, nom: "Njə́ə̀kwɑ̀", jour: "Tuesday", nufiJour: "Ncômntēē" },
  { numero: 14, nom: "Njə̀ə̄mōō", jour: "Wednesday", nufiJour: "Nzîngū" },
  { numero: 15, nom: "Ndə̀ə̄nkām", jour: "Thursday", nufiJour: "Nzîsō" },
  { numero: 16, nom: "Njòōmbísīē", jour: "Friday", nufiJour: "Nsū'kwɑ̀" },
  { numero: 17, nom: "Fǎ'nkām", jour: "Saturday", nufiJour: "Nthʉ̄'ntāā" },
  { numero: 18, nom: "Fə̌' yò", jour: "Sunday", nufiJour: "Líé'nkwè’" },
  { numero: 19, nom: "Hɑ̄àpìì", jour: "Monday", nufiJour: "NKɑ́ɑ́tēē" },
  { numero: 20, nom: "Njînù", jour: "Tuesday", nufiJour: "Nzêngòò" },
  { numero: 21, nom: "Ǹ kɑ̀' zhī", jour: "Wednesday", nufiJour: "Ncômntēē" },
  { numero: 22, nom: "Ǹ kɑ̀' kɑ́' nù", jour: "Thursday", nufiJour: "Nzîngū" },
  { numero: 23, nom: "Nkǎkmɑ̄nì", jour: "Friday", nufiJour: "Nzîsō" },
  { numero: 24, nom: "Nkɑ̀'ncò", jour: "Saturday", nufiJour: "Nsū'kwɑ̀" },
  { numero: 25, nom: "Kɑ́ mbí wɑ̄", jour: "Sunday", nufiJour: "Nthʉ̄'ntāā" },
  { numero: 26, nom: "Kèēwū", jour: "Monday", nufiJour: "Líé'nkwè’" },
  { numero: 27, nom: "Kwèlě'kò", jour: "Tuesday", nufiJour: "NKɑ́ɑ́tēē" },
  { numero: 28, nom: "Zhínù", jour: "Wenesday", nufiJour: "Nzêngòò" },
  { numero: 29, nom: "Mīàfə̀", jour: "Thursday", nufiJour: "Ncômntēē" },
  { numero: 30, nom: "Mbàtkām", jour: "Friday", nufiJour: "Nzîngū" },
];

export default PersonnesJuin;
