const personnesMars = [
  { numero: 1, nom: "Ngà'fʉ̀'", jour: "Wednesday"  },
  { numero: 2, nom: "Ngǎngǎ mìè" , jour: "Thursday" },
  { numero: 3, nom: "Ngòò Mbūànì" , jour: "Friday" },
  { numero: 4, nom: "Ngʉ̀'" , jour: "Saturday" },
  { numero: 5, nom: "Ngʉ̀' zǎ" , jour: "Sunday" },
  { numero: 6, nom: "Ngʉ̀' zǎ mbú ò" , jour: "Monday" },
  { numero: 7, nom: "Ngʉ́ɑ́' yá' mìè" , jour: "Tuesday" },
  { numero: 8, nom: "Ngʉ̌' Vɑ̀h" , jour: "Wednesday" },
  { numero: 9, nom: "Njû'nì" , jour: "Thursday" },
  { numero: 10, nom: "Nkɑ̀'" , jour: "Friday" },
  { numero: 11, nom: "Nkɑ̌' Ndéndēē" , jour: "Saturday" },
  { numero: 12, nom: "Nkɑ́' Ngwè'" , jour: "Sunday" },
  { numero: 13, nom: "Nkɑ̌' Vɑ̀h" , jour: "Monday" },
  { numero: 14, nom: "Nkèn Fī" , jour: "Tuesday" },
  { numero: 15, nom: "Nkômbhìnù" , jour: "Wednesday" },
  { numero: 16, nom: "Nkômnā" , jour: "Thursday" },
  { numero: 17, nom: "Nkù'nì", jour: "Friday"  },
  { numero: 18, nom: "Nkwà'nù" , jour: "Saturday" },
  { numero: 19, nom: "Nkwèè yà Fʉ̀'" , jour: "Sunday" },
  { numero: 20, nom: "Nkwèè yà ngʉ̀'" , jour: "Monday" },
  { numero: 21, nom: "Nkwè'nì / Nkə̀'nì" , jour: "Tuesday" },
  { numero: 22, nom: "Nkwè'nì lɑ̀' míé", jour: "Wednesday"  },
  { numero: 23, nom: "Nkwè'nì lɑ̀ pé'" , jour: "Thursday" },
  { numero: 24, nom: "Nkwè'nì pōōntìā" , jour: "Friday" },
  { numero: 25, nom: "Nsə̀ə̀ Fī" , jour: "Saturday" },
  { numero: 26, nom: "Nsə̀ə̀ mā" , jour: "Sunday" },
  { numero: 27, nom: "Nshǐvɑ̀h" , jour: "Monday" },
  { numero: 28, nom: "Nshʉ̀ɑ̀ncò" , jour: "Tuesday" },
  { numero: 29, nom: "Nshù'gwè'", jour: "Wednesday"  },
  { numero: 30, nom: "Nshwînā" , jour: "Thursday" },
  { numero: 31, nom: "Shwīnāò" , jour: "Friday" },
];

export default personnesMars;
