const PersonnesJuin = [
  { numero: 1, nom: "Mbàkngòfāt", jour: "Thursday" },
  { numero: 2, nom: "Mbɑ̀ lāhā lɑ̄", jour: "Friday" },
  { numero: 3, nom: "Mbǔ'zhíkɑ́", jour: "Saturday" },
  { numero: 4, nom: "Mbósīē", jour: "Sunday" },
  { numero: 5, nom: "Mbóncâk", jour: "Monday" },
  { numero: 6, nom: "Mbōòwèn", jour: "Tuesday" },
  { numero: 7, nom: "Shʉ̄cwɑ̀'", jour: "Wednesday" },
  { numero: 8, nom: "Nshǔndênù", jour: "Thursday" },
  { numero: 9, nom: "Ndɑ̌'kɑ́yīī", jour: "Friday" },
  { numero: 10, nom: "Ndɑ̌'sīē", jour: "Saturday" },
  { numero: 11, nom: "Ǹ dɑ̀yíí nù", jour: "Sunday" },
  { numero: 12, nom: "Ndʉɑ̀pèè", jour: "Monday" },
  { numero: 13, nom: "Njə́ə̀kwɑ̀", jour: "Tuesday" },
  { numero: 14, nom: "Njə̀ə̄mōō", jour: "Wednesday" },
  { numero: 15, nom: "Zhìāndə̀ə̀", jour: "Thursday" },
  { numero: 16, nom: "Njòōmbísīē", jour: "Friday" },
  { numero: 17, nom: "Fǎ'nkām", jour: "Saturday" },
  { numero: 18, nom: "Fə̌' yò", jour: "Sunday" },
  { numero: 19, nom: "Hɑ̄àpìì", jour: "Monday" },
  { numero: 20, nom: "Njînù", jour: "Tuesday" },
  { numero: 21, nom: "Ǹ kɑ̀' zhī", jour: "Wednesday" },
  { numero: 22, nom: "Ǹ kɑ̀' kɑ́' nù", jour: "Thursday" },
  { numero: 23, nom: "Nkǎkmɑ̄nì", jour: "Friday" },
  { numero: 24, nom: "Nkɑ̀'ncò", jour: "Saturday" },
  { numero: 25, nom: "Kɑ́ mbí wɑ̄", jour: "Sunday" },
  { numero: 26, nom: "Kèēwū / Sə̀ə̄wū", jour: "Monday" },
  { numero: 27, nom: "Kwèlě'kò", jour: "Tuesday" },
  { numero: 28, nom: "Zhínù", jour: "Wenesday" },
  { numero: 29, nom: "Zʉ́sóh Nkwè'nì", jour: "Thursday" },
  { numero: 30, nom: "Mbàtkām", jour: "Friday" },
];

export default PersonnesJuin;
